### PR TITLE
Refactor feature extraction

### PR DESCRIPTION
**Pull request by rth**
Following the discussion in  #1 , this PR proposes a refactoring and simplification of the feature extraction in the starting kit,
  * the custom tokenization, stemming with nltk are removed and the feature ingestion corresponds to `TfidfVectorizer` with default parameters.
  * added preprocessing and token processing functions that would allow reproducing the previous behavior with stemming etc. These functions are left empty.
  * added a short description in the beginning of the file with indications which parts of the code can be changed to tune feature extraction.

Also changed the number of CV folds from 8 to 5. I don't think that this changes the accuracy much, but it's helpful to have a lower runtime to allow faster iterations when experimenting. 

Before this PR, the `ramp_test_submission` produces,
```
train sacc = 0.76 ± 0.002
train acc = 0.988 ± 0.001
train tfacc = 0.832 ± 0.001
valid sacc = 0.337 ± 0.006
valid acc = 0.213 ± 0.022
valid tfacc = 0.537 ± 0.007
test sacc = 0.339 ± 0.002
test acc = 0.207 ± 0.006
test tfacc = 0.537 ± 0.002

ramp_test_submission  245.99s
```
while with the code in this PR, we get,
```
train sacc = 0.758 ± 0.001
train acc = 0.99 ± 0.001
train tfacc = 0.831 ± 0.002
valid sacc = 0.333 ± 0.004
valid acc = 0.216 ± 0.006
valid tfacc = 0.534 ± 0.005
test sacc = 0.333 ± 0.002
test acc = 0.201 ± 0.006
test tfacc = 0.532 ± 0.002

ramp_test_submission  50.08s
```

so the test and validation accuracy are sensibly similar, while the run time is reduced by a factor of ~5.

Please let me know if you have any comments @EmanuelaBoros @kegl @vlagani @jorisvandenbossche ..

**Edit:** PY2 build fails, with,
```
Error: HTTPError: 530 Server Error: : http://repo.continuum.io/pkgs/free/linux-64/idna-2.6-py27_0.tar.bz2
```
when downloading the dependencies, will retry later, maybe it's just a temporary issue.

### CODE REVIEW

**Comment by kegl** [comment]
The CV is already decided and in the DB on ramp.studio. 8 is sort of our default if the data is not too big. It also makes the contributivity score smoother. Otherwise I like it, it's simpler.

We'll also need the notebook updated (right now it is the "master", using the %%file decorator to overwrite the starting kit). It would also be nice to give some step-by-step examples and explanation on the preprocessing there. Thanks a lot for this we'll put you as a coauthor on the notebook.

**Comment by rth** [comment]
Thanks for the review @kegl !

> The CV is already decided and in the DB on ramp.studio. 8 is sort of our default if the data is not too big. 

OK, I reverted this change.

> We'll also need the notebook updated (right now it is the "master", using the %%file decorator to overwrite the starting kit). It would also be nice to give some step-by-step examples and explanation on the preprocessing there.

Updated the code in the notebook. I refactored and extended the existing explanations on feature ingestion in the notebook. They might need another read to smooth things over..

Also fixed a few typos.

**Comment by kegl** [comment]
1. Add your name to the author list (unless you don't want)
2. A stupid little cosmetics issue: in %%file cells you'll need to add _two_ new lines at the end, which generates a _single_ new line in the file (so flake doesn't complain).

@EmanuelaBoros can you take a look before we merge?

**Comment by rth** [comment]
> Add your name to the author list (unless you don't want)
> A stupid little cosmetics issue: in %%file cells you'll need to add two new lines at the end, which generates a single new line in the file (so flake doesn't complain)

Done. I was wondering about how to make the second point work with flake, thanks..

**Comment by kegl** [comment]
Just add two new lines at the end of the cell.

**Comment by rth** [comment]
> Just add two new lines at the end of the cell.

@kegl Not sure where: the conflict was due to the changed url in notebook on `master`. Maybe I missed something. In any case, this should be resolved now.

 
@EmanuelaBoros Would you be able to review this PR? Thanks!

**Pull request merged**
